# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
absl-py=1.3.0=py37h06a4308_0
aiohttp=3.8.3=py37h5eee18b_0
aiosignal=1.2.0=pyhd3eb1b0_0
antlr4-python3-runtime=4.9.3=pypi_0
appdirs=1.4.4=pypi_0
async-timeout=4.0.2=py37h06a4308_0
asynctest=0.13.0=py_0
attrs=22.1.0=py37h06a4308_0
audioread=3.0.1=pypi_0
backcall=0.2.0=pypi_0
black=21.4b2=pypi_0
blas=1.0=mkl
blinker=1.4=py37h06a4308_0
blis=0.7.11=pypi_0
blosc=1.21.3=h6a678d5_0
boto3=1.21.32=pyhd3eb1b0_0
botocore=1.24.32=pyhd3eb1b0_0
bottleneck=1.3.5=py37h7deecbd_0
brotli=1.0.9=h5eee18b_7
brotli-bin=1.0.9=h5eee18b_7
brotlipy=0.7.0=py37h27cfd23_1003
brunsli=0.1=h2531618_0
bzip2=1.0.8=h7b6447c_0
c-ares=1.19.1=h5eee18b_0
ca-certificates=2023.08.22=h06a4308_0
cachetools=4.2.2=pyhd3eb1b0_0
calflops=0.2.0=pypi_0
catalogue=2.0.9=pypi_0
certifi=2020.6.20=pyhd3eb1b0_3
cffi=1.15.1=py37h5eee18b_3
cfitsio=3.470=h5893167_7
charls=2.2.0=h2531618_0
charset-normalizer=2.0.4=pyhd3eb1b0_0
click=8.0.4=py37h06a4308_0
clip=1.0=pypi_0
cloudpickle=2.0.0=pyhd3eb1b0_0
conda-pack=0.7.0=pyh6c4a22f_0
confection=0.1.3=pypi_0
cryptography=39.0.1=py37h9ce1e76_0
cudatoolkit=11.3.1=h2bc3f7f_2
cycler=0.11.0=pyhd3eb1b0_0
cymem=2.0.8=pypi_0
cytoolz=0.12.0=py37h5eee18b_0
dask-core=2021.10.0=pyhd3eb1b0_0
dbus=1.13.18=hb2f20db_0
decorator=4.4.2=pypi_0
deepspeed=0.14.0=pypi_0
docker-pycreds=0.4.0=pypi_0
easydict=1.10=pypi_0
einops=0.6.1=pyhd8ed1ab_0
en-core-web-lg=3.5.0=pypi_0
exceptiongroup=1.2.0=pypi_0
expat=2.4.9=h6a678d5_0
ffmpeg=4.3=hf484d3e_0
fftw=3.3.9=h27cfd23_1
filelock=3.12.2=pypi_0
fontconfig=2.14.1=h52c9d5c_1
fonttools=4.25.0=pyhd3eb1b0_0
freetype=2.12.1=h4a9f257_0
frozenlist=1.3.3=py37h5eee18b_0
fsspec=2022.11.0=py37h06a4308_0
ftfy=6.1.1=pypi_0
future=0.18.3=pypi_0
fvcore=0.1.5.post20221221=pypi_0
giflib=5.2.1=h5eee18b_3
gitdb=4.0.11=pypi_0
gitpython=3.1.42=pypi_0
glib=2.69.1=he621ea3_2
gmp=6.2.1=h295c915_3
gnutls=3.6.15=he1e5248_0
google-auth=2.6.0=pyhd3eb1b0_0
google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
gpuinfo=1.0.0a7=pypi_0
grpcio=1.42.0=py37hce63b2e_0
gst-plugins-base=1.14.1=h6a678d5_1
gstreamer=1.14.1=h5eee18b_1
h5py=3.7.0=py37h737f45e_0
hdf5=1.10.6=h3ffc7dd_1
hjson=3.1.0=pypi_0
huggingface-hub=0.16.4=pypi_0
hydra-core=1.3.2=pypi_0
icu=58.2=he6710b0_3
idna=3.4=py37h06a4308_0
imagecodecs=2021.8.26=py37hfcb8610_2
imageio=2.19.3=py37h06a4308_0
imageio-ffmpeg=0.4.9=pypi_0
importlib-metadata=4.11.3=py37h06a4308_0
importlib-resources=5.12.0=pypi_0
iniconfig=2.0.0=pypi_0
intel-openmp=2021.4.0=h06a4308_3561
iopath=0.1.9=pypi_0
ipdb=0.13.13=pypi_0
ipython=7.34.0=pypi_0
jedi=0.19.1=pypi_0
jinja2=3.1.2=pypi_0
jmespath=0.10.0=pyhd3eb1b0_0
joblib=1.1.1=py37h06a4308_0
jpeg=9e=h5eee18b_1
jxrlib=1.1=h7b6447c_2
kiwisolver=1.4.4=py37h6a678d5_0
krb5=1.19.4=h568e23c_0
lame=3.100=h7b6447c_0
langcodes=3.3.0=pypi_0
lazy-loader=0.3=pypi_0
lcms2=2.12=h3be6417_0
ld_impl_linux-64=2.38=h1181459_1
lerc=3.0=h295c915_0
libaec=1.0.4=he6710b0_1
libbrotlicommon=1.0.9=h5eee18b_7
libbrotlidec=1.0.9=h5eee18b_7
libbrotlienc=1.0.9=h5eee18b_7
libclang=10.0.1=default_hb85057a_2
libcurl=8.1.1=h91b91d3_0
libdeflate=1.17=h5eee18b_0
libedit=3.1.20221030=h5eee18b_0
libev=4.33=h7f8727e_1
libevent=2.1.12=h8f2d780_0
libffi=3.4.2=h6a678d5_6
libgcc-ng=11.2.0=h1234567_1
libgfortran-ng=11.2.0=h00389a5_1
libgfortran5=11.2.0=h1234567_1
libgomp=11.2.0=h1234567_1
libiconv=1.16=h7f8727e_2
libidn2=2.3.2=h7f8727e_0
libllvm10=10.0.1=hbcb73fb_5
libnghttp2=1.52.0=ha637b67_1
libpng=1.6.39=h5eee18b_0
libpq=12.9=h16c4e8d_3
libprotobuf=3.20.3=he621ea3_0
librosa=0.10.1=pypi_0
libssh2=1.10.0=h37d81fd_2
libstdcxx-ng=11.2.0=h1234567_1
libtasn1=4.16.0=h27cfd23_0
libtiff=4.5.0=h6a678d5_2
libunistring=0.9.10=h27cfd23_0
libuuid=1.41.5=h5eee18b_0
libwebp=1.2.4=h11a3e52_1
libwebp-base=1.2.4=h5eee18b_1
libxcb=1.15=h7f8727e_0
libxkbcommon=1.0.1=hfa300c1_0
libxml2=2.9.14=h74e7548_0
libxslt=1.1.35=h4e12654_0
libzopfli=1.0.3=he6710b0_0
llvmlite=0.39.1=pypi_0
locket=1.0.0=py37h06a4308_0
loralib=0.1.2=pypi_0
lz4-c=1.9.4=h6a678d5_0
markdown=3.4.1=py37h06a4308_0
markupsafe=2.1.3=pypi_0
matplotlib=3.5.3=py37h06a4308_0
matplotlib-base=3.5.3=py37hf590b9c_0
matplotlib-inline=0.1.6=pypi_0
mkl=2021.4.0=h06a4308_640
mkl-service=2.4.0=py37h7f8727e_0
mkl_fft=1.3.1=py37hd3c417c_0
mkl_random=1.2.2=py37h51133e4_0
moviepy=1.0.3=pypi_0
msgpack=1.0.5=pypi_0
multidict=6.0.2=py37h5eee18b_0
munch=4.0.0=pypi_0
munkres=1.1.4=py_0
murmurhash=1.0.10=pypi_0
mypy-extensions=1.0.0=pypi_0
ncurses=6.4=h6a678d5_0
nettle=3.7.3=hbbd107a_1
networkx=2.6.3=pyhd3eb1b0_0
ninja=1.11.1.1=pypi_0
nspr=4.33=h295c915_0
nss=3.74=h0370c37_0
numba=0.56.4=pypi_0
numexpr=2.8.4=py37he184ba9_0
numpy=1.21.5=py37h6c91a56_3
numpy-base=1.21.5=py37ha15fc14_3
oauthlib=3.2.1=py37h06a4308_0
omegaconf=2.3.0=pypi_0
opencv-python-headless=4.8.0.76=py37_0
openh264=2.1.1=h4ff587b_0
openjpeg=2.4.0=h3ad879b_0
openssl=1.1.1w=h7f8727e_0
packaging=22.0=py37h06a4308_0
pandas=1.3.5=py37h8c16a72_0
parso=0.8.3=pypi_0
partd=1.2.0=pyhd3eb1b0_1
pathspec=0.11.2=pypi_0
pathtools=0.1.2=pypi_0
pathy=0.10.2=pypi_0
pcre=8.45=h295c915_0
pexpect=4.8.0=pypi_0
pickleshare=0.7.5=pypi_0
pillow=9.5.0=pypi_0
pip=22.3.1=py37h06a4308_0
platformdirs=3.0.0=pypi_0
pluggy=1.2.0=pypi_0
ply=3.11=py37_0
pooch=1.7.0=pypi_0
portalocker=2.7.0=pypi_0
preshed=3.0.9=pypi_0
proglog=0.1.10=pypi_0
promise=2.3=pypi_0
prompt-toolkit=3.0.39=pypi_0
protobuf=3.19.6=pypi_0
psutil=5.9.8=pypi_0
ptyprocess=0.7.0=pypi_0
py-cpuinfo=9.0.0=pypi_0
pyasn1=0.4.8=pyhd3eb1b0_0
pyasn1-modules=0.2.8=py_0
pycocotools=2.0.7=pypi_0
pycparser=2.21=pyhd3eb1b0_0
pydantic=1.10.11=pypi_0
pydot=1.4.2=pypi_0
pygments=2.16.1=pypi_0
pyjwt=2.4.0=py37h06a4308_0
pynvml=11.5.0=pypi_0
pyopenssl=23.0.0=py37h06a4308_0
pyparsing=3.0.9=py37h06a4308_0
pyqt=5.15.7=py37h6a678d5_1
pyqt5-sip=12.11.0=py37h6a678d5_1
pysocks=1.7.1=py37_1
pytest=7.4.4=pypi_0
python=3.7.16=h7a1cb2a_0
python-dateutil=2.8.2=pyhd3eb1b0_0
pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
pytorch-mutex=1.0=cuda
pytz=2022.7=py37h06a4308_0
pywavelets=1.3.0=py37h7f8727e_0
pyyaml=6.0=py37h5eee18b_1
qt-main=5.15.2=h327a75a_7
qt-webengine=5.15.9=hd2b0992_4
qtwebkit=5.212=h4eab89a_4
readline=8.2=h5eee18b_0
regex=2023.8.8=pypi_0
requests=2.28.1=py37h06a4308_0
requests-oauthlib=1.3.0=py_0
resampy=0.4.2=pypi_0
rsa=4.7.2=pyhd3eb1b0_1
ruamel=1.0=py37h06a4308_2
ruamel-yaml=0.18.5=pypi_0
ruamel-yaml-clib=0.2.8=pypi_0
s3transfer=0.5.0=pyhd3eb1b0_0
safetensors=0.3.3=pypi_0
scikit-image=0.19.3=py37h6a678d5_1
scikit-learn=1.0.2=py37h51133e4_1
scipy=1.7.3=py37h6c91a56_2
seaborn=0.12.2=pypi_0
sentry-sdk=1.43.0=pypi_0
setproctitle=1.3.3=pypi_0
setuptools=65.6.3=py37h06a4308_0
shortuuid=1.0.13=pypi_0
sip=6.6.2=py37h6a678d5_0
six=1.16.0=pyhd3eb1b0_1
smart-open=6.4.0=pypi_0
smmap=5.0.1=pypi_0
snappy=1.1.9=h295c915_0
soundfile=0.12.1=pypi_0
soxr=0.3.7=pypi_0
spacy=3.5.2=pypi_0
spacy-legacy=3.0.12=pypi_0
spacy-loggers=1.0.5=pypi_0
sqlite=3.41.1=h5eee18b_0
srsly=2.4.8=pypi_0
tabulate=0.9.0=pypi_0
tensorboard=2.10.0=py37h06a4308_0
tensorboard-data-server=0.6.1=py37h52d8a92_0
tensorboard-plugin-wit=1.8.1=py37h06a4308_0
tensorboardx=2.2=pyhd3eb1b0_0
termcolor=2.3.0=pypi_0
thinc=8.1.12=pypi_0
thop=0.1.1-2209072238=pypi_0
threadpoolctl=2.2.0=pyh0d69192_0
tifffile=2021.7.2=pyhd3eb1b0_2
timm=0.6.7=pypi_0
tk=8.6.12=h1ccaba5_0
tokenizers=0.13.3=pypi_0
toml=0.10.2=pyhd3eb1b0_0
tomli=2.0.1=pypi_0
toolz=0.12.0=py37h06a4308_0
torchaudio=0.12.1=py37_cu113
torchlibrosa=0.1.0=pypi_0
torchvggish=0.2=pypi_0
torchvision=0.13.1=py37_cu113
tornado=6.2=py37h5eee18b_0
tqdm=4.66.1=pypi_0
traitlets=5.9.0=pypi_0
transformers=4.26.1=pypi_0
typed-ast=1.5.5=pypi_0
typer=0.7.0=pypi_0
typing-extensions=4.7.1=pypi_0
urllib3=1.26.14=py37h06a4308_0
vit-pytorch=1.5.1=pypi_0
wandb=0.13.3=pypi_0
wasabi=1.1.2=pypi_0
wcwidth=0.2.6=pypi_0
werkzeug=2.2.2=py37h06a4308_0
wget=3.2=pypi_0
wheel=0.38.4=py37h06a4308_0
xz=5.2.10=h5eee18b_1
yacs=0.1.8=pypi_0
yaml=0.2.5=h7b6447c_0
yarl=1.8.1=py37h5eee18b_0
zfp=0.5.5=h295c915_6
zipp=3.11.0=py37h06a4308_0
zlib=1.2.13=h5eee18b_0
zstd=1.5.2=ha4553b6_0
